import {cp,mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const raw=process.env.BACKEND_ORIGIN;
if(!raw)throw Error('Set BACKEND_ORIGIN to your persistent HTTPS backend before building. Netlify Drop alone cannot run the database.');
const origin=new URL(raw);
if(origin.protocol!=='https:'||origin.username||origin.password||origin.pathname!=='/'||origin.search||origin.hash||['localhost','127.0.0.1'].includes(origin.hostname))throw Error('BACKEND_ORIGIN must be a plain public HTTPS origin.');
const output=resolve('netlify-site');await mkdir(output,{recursive:true});await cp('public',output,{recursive:true});
await writeFile(resolve(output,'_redirects'),`/api/* ${origin.origin}/api/:splat 200!\n/uploads/* ${origin.origin}/uploads/:splat 200!\n/* /index.html 200\n`);
await writeFile(resolve(output,'_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: no-referrer\n  X-Frame-Options: DENY\n  Cache-Control: no-store\n');
console.log('Upload only netlify-site to Netlify Drop. Backend BASE_URL must be your exact Netlify HTTPS origin.');
